"""fix posts

Revision ID: 45fbde60516b
Revises: eee78041f909
Create Date: 2023-06-23 17:47:10.019541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45fbde60516b'
down_revision = 'eee78041f909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_counter', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
